name: sat_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-146.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #cupertino icons
  cupertino_icons: ^1.0.2
  #google fonts
  google_fonts: ^3.0.1
  #animations
  animated_text_kit: ^4.2.2
  #image
  image_picker: ^0.8.6+1
  #firebase
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_core: ^2.4.1
  uuid: ^3.0.7
  #grid
  staggered_grid_view_flutter: ^0.0.4
  #others
  flutter_swiper_null_safety: ^1.0.2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/men/
    - images/try/
    - images/inapp/
    - images/women/
    - images/shoes/
    - images/electronics/
    - images/beauty/
    - images/kids/
    - images/homegarden/
    - images/accessories/
    - images/bags/

  fonts:
    - family: Acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
